db:
  host: 88.99.0.81
  port: 3306
  username: smsforbet_admin
  db_name: smsforbet
  password: j0M.wYW!M0&Ym-QyM2U$
site_meta:
  login_url: http://www.dakikpanel1.com/login
  username: 8503352153
  password: 4pv21w
  post_url: http://www.dakikpanel1.com/toplumesaj/toplumesajgonder
  optimize_resource_fetch: false
app_config:
  page_size: 10
